### ISSUE TITLE
Sidebar Location

### ISSUE THREAD

**Issue by Adyyda** [osclass/theme-bender#50]
In sidebar, when we start to type a location, if we have duplicated city and different region, will show as City (Region) in the dropdown, but after we select the option,  (Region) is gone. Please show it final as it shows in dropdown so users see what they selected.

![1](https://cloud.githubusercontent.com/assets/5921012/12531750/6aca8d9c-c20b-11e5-9531-21cfeb4cd0e0.png)
![11](https://cloud.githubusercontent.com/assets/5921012/12531752/6e537956-c20b-11e5-82c1-d84aee6f508a.png)

**Comment by Adyyda** [comment]
In addition, if we selected in admin area to see location as dropdown, that should reflect as well in the sidebar?

**Comment by garciademarina** [comment]
already fixed at Osclass core
