### ISSUE TITLE
Filter ads from one region

### ISSUE THREAD

**Issue by Adyyda** [osclass/theme-bender#51]
Hello. Please go to https://demo.osclass.org/general/index.php?page=search&sRegion=3

As you can see, i have selected from home page the location Barcelona.
If you click in sidebar on category, to filter the listings, all is fine. We see results from Vehicles (for instance) only from Barcelona.

Now, go and filter them by price or by pictures and you will see that the whole filtering is changed. Barcelona is gone and we see results from all regions.

If we started from one location, all filters must apply to that location.

**Comment by garciademarina** [comment]
no issue
