### ISSUE TITLE
invalid css propertly

### ISSUE THREAD

**Issue by dev-101** [osclass/theme-bender#54]
auto\9 @ main.css

`img{max-width:100%;width:auto\9;height:auto;vertical-align:middle;border:0;-ms-interpolation-mode:bicubic}`

**Comment by garciademarina** [comment]
> That's an IE hack, and is meant to be there.

https://github.com/twbs/bootstrap/issues/7751

**Comment by dev-101** [comment]
I think I had a problem with this in some browser (IE probably), that's why I reported it, sorry, I don't recall anymore what the issue was.

I think this hack is way too old and should be removed.

**Comment by dev-101** [comment]
Thanks
